export interface YouTubeCaptionTrack {
  baseUrl: string;
  languageCode?: string;
  name?: string;
  isAutoGenerated: boolean;
}

export interface YouTubeCaptionCue {
  id: string;
  startMs: number;
  durationMs: number;
  text: string;
}

interface PlayerResponse {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: Array<{
        baseUrl?: string;
        languageCode?: string;
        kind?: string;
        name?: { simpleText?: string; runs?: Array<{ text?: string }> };
      }>;
    };
  };
}

interface Json3TimedText {
  events?: Array<{
    tStartMs?: number;
    dDurationMs?: number;
    segs?: Array<{ utf8?: string }>;
  }>;
}

export function extractYouTubeCaptionTracks(documentRoot: Document = document): YouTubeCaptionTrack[] {
  const response = extractPlayerResponse(documentRoot);
  return getCaptionTracksFromPlayerResponse(response);
}

export async function discoverYouTubeCaptionTracks(
  documentRoot: Document = document,
  pageUrl: string = location.href
): Promise<YouTubeCaptionTrack[]> {
  const embeddedTracks = extractYouTubeCaptionTracks(documentRoot);
  if (embeddedTracks.length > 0) {
    return embeddedTracks;
  }

  const response = await fetch(pageUrl);
  if (!response.ok) {
    return [];
  }

  const html = await response.text();
  const fetchedDocument = new DOMParser().parseFromString(html, "text/html");
  return extractYouTubeCaptionTracks(fetchedDocument);
}

function getCaptionTracksFromPlayerResponse(response: PlayerResponse | undefined): YouTubeCaptionTrack[] {
  const tracks = response?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];

  return tracks
    .filter((track): track is Required<Pick<typeof track, "baseUrl">> & typeof track => Boolean(track.baseUrl))
    .map((track) => ({
      baseUrl: track.baseUrl,
      languageCode: track.languageCode,
      name: getTrackName(track.name),
      isAutoGenerated: track.kind === "asr"
    }));
}

export function choosePreferredCaptionTrack(tracks: YouTubeCaptionTrack[]): YouTubeCaptionTrack | undefined {
  return tracks.find((track) => !track.isAutoGenerated) ?? tracks[0];
}

export async function fetchYouTubeCaptionCues(track: YouTubeCaptionTrack): Promise<YouTubeCaptionCue[]> {
  const response = await fetch(getJson3TimedTextUrl(track.baseUrl));
  if (!response.ok) {
    throw new Error(`Caption track request failed with ${response.status}.`);
  }

  const contentType = response.headers.get("content-type") ?? "";
  const text = await response.text();
  if (contentType.includes("application/json") || text.trimStart().startsWith("{")) {
    return parseJson3CaptionCues(JSON.parse(text) as Json3TimedText);
  }
  return parseXmlCaptionCues(text);
}

export function parseJson3CaptionCues(payload: Json3TimedText): YouTubeCaptionCue[] {
  return (payload.events ?? [])
    .map((event, index) => {
      const text = normalizeCaptionText((event.segs ?? []).map((segment) => segment.utf8 ?? "").join(""));
      return {
        id: `cue-${index}`,
        startMs: event.tStartMs ?? 0,
        durationMs: event.dDurationMs ?? 0,
        text
      };
    })
    .filter((cue) => cue.text.length > 0);
}

export function parseXmlCaptionCues(xml: string): YouTubeCaptionCue[] {
  const documentRoot = new DOMParser().parseFromString(xml, "text/xml");
  return Array.from(documentRoot.querySelectorAll("text"), (node, index) => {
    const startMs = secondsToMs(node.getAttribute("start"));
    const durationMs = secondsToMs(node.getAttribute("dur"));
    return {
      id: `cue-${index}`,
      startMs,
      durationMs,
      text: normalizeCaptionText(node.textContent ?? "")
    };
  }).filter((cue) => cue.text.length > 0);
}

function extractPlayerResponse(documentRoot: Document): PlayerResponse | undefined {
  const scripts = Array.from(documentRoot.scripts, (script) => script.textContent ?? "");
  for (const script of scripts) {
    const response = extractJsonAssignment<PlayerResponse>(script, "ytInitialPlayerResponse");
    if (response) {
      return response;
    }
  }
  return undefined;
}

function extractJsonAssignment<T>(script: string, variableName: string): T | undefined {
  const assignmentIndex = script.indexOf(variableName);
  if (assignmentIndex < 0) {
    return undefined;
  }

  const objectStart = script.indexOf("{", assignmentIndex);
  if (objectStart < 0) {
    return undefined;
  }

  const json = readBalancedJsonObject(script, objectStart);
  if (!json) {
    return undefined;
  }
  return JSON.parse(json) as T;
}

function readBalancedJsonObject(source: string, startIndex: number): string | undefined {
  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let index = startIndex; index < source.length; index += 1) {
    const char = source[index];
    if (escaped) {
      escaped = false;
      continue;
    }
    if (char === "\\") {
      escaped = inString;
      continue;
    }
    if (char === '"') {
      inString = !inString;
      continue;
    }
    if (inString) {
      continue;
    }
    if (char === "{") {
      depth += 1;
    } else if (char === "}") {
      depth -= 1;
      if (depth === 0) {
        return source.slice(startIndex, index + 1);
      }
    }
  }
  return undefined;
}

function getJson3TimedTextUrl(baseUrl: string): string {
  const url = new URL(baseUrl);
  url.searchParams.set("fmt", "json3");
  return url.toString();
}

function getTrackName(name?: { simpleText?: string; runs?: Array<{ text?: string }> }): string | undefined {
  return name?.simpleText ?? name?.runs?.map((run) => run.text ?? "").join("").trim() ?? undefined;
}

function secondsToMs(value: string | null): number {
  const seconds = Number(value);
  return Number.isFinite(seconds) ? Math.round(seconds * 1000) : 0;
}

function normalizeCaptionText(text: string): string {
  return decodeHtmlEntities(text).replace(/\s+/g, " ").trim();
}

function decodeHtmlEntities(text: string): string {
  const textarea = document.createElement("textarea");
  textarea.innerHTML = text;
  return textarea.value;
}
