import { beforeEach, describe, expect, it, vi } from "vitest";
import {
  choosePreferredCaptionTrack,
  discoverYouTubeCaptionTracks,
  extractYouTubeCaptionTracks,
  fetchYouTubeCaptionCues,
  parseJson3CaptionCues,
  parseXmlCaptionCues
} from "./captionTracks";

beforeEach(() => {
  document.body.innerHTML = "";
  vi.restoreAllMocks();
});

describe("extractYouTubeCaptionTracks", () => {
  it("extracts caption tracks from ytInitialPlayerResponse", () => {
    document.body.innerHTML = `
      <script>
        var ytInitialPlayerResponse = {
          "captions": {
            "playerCaptionsTracklistRenderer": {
              "captionTracks": [
                {
                  "baseUrl": "https://www.youtube.com/api/timedtext?v=abc&lang=en",
                  "languageCode": "en",
                  "name": { "simpleText": "English" }
                },
                {
                  "baseUrl": "https://www.youtube.com/api/timedtext?v=abc&lang=en&kind=asr",
                  "languageCode": "en",
                  "kind": "asr",
                  "name": { "runs": [{ "text": "English auto-generated" }] }
                }
              ]
            }
          }
        };
      </script>
    `;

    expect(extractYouTubeCaptionTracks()).toEqual([
      {
        baseUrl: "https://www.youtube.com/api/timedtext?v=abc&lang=en",
        languageCode: "en",
        name: "English",
        isAutoGenerated: false
      },
      {
        baseUrl: "https://www.youtube.com/api/timedtext?v=abc&lang=en&kind=asr",
        languageCode: "en",
        name: "English auto-generated",
        isAutoGenerated: true
      }
    ]);
  });

  it("handles scripts without a player response", () => {
    document.body.innerHTML = `<script>window.__other = {"captions": {}};</script>`;

    expect(extractYouTubeCaptionTracks()).toEqual([]);
  });

  it("ignores incomplete player response assignments", () => {
    document.body.innerHTML = `<script>var ytInitialPlayerResponse = window.__missing;</script>`;

    expect(extractYouTubeCaptionTracks()).toEqual([]);
  });

  it("ignores unbalanced player response assignments", () => {
    document.body.innerHTML = `<script>var ytInitialPlayerResponse = {"captions": {"broken": true;</script>`;

    expect(extractYouTubeCaptionTracks()).toEqual([]);
  });

  it("handles braces and escaped quotes inside player response strings", () => {
    document.body.innerHTML = `
      <script>
        var ytInitialPlayerResponse = {
          "captions": {
            "playerCaptionsTracklistRenderer": {
              "captionTracks": [
                {
                  "baseUrl": "https://www.youtube.com/api/timedtext?v=abc&lang=en",
                  "name": { "simpleText": "English \\"{manual}\\"" }
                }
              ]
            }
          }
        }; window.after = {"ignored": true};
      </script>
    `;

    expect(extractYouTubeCaptionTracks()).toEqual([
      {
        baseUrl: "https://www.youtube.com/api/timedtext?v=abc&lang=en",
        languageCode: undefined,
        name: 'English "{manual}"',
        isAutoGenerated: false
      }
    ]);
  });

  it("prefers manual captions over auto-generated captions", () => {
    expect(
      choosePreferredCaptionTrack([
        { baseUrl: "https://example.com/asr", isAutoGenerated: true },
        { baseUrl: "https://example.com/manual", isAutoGenerated: false }
      ])
    ).toMatchObject({ baseUrl: "https://example.com/manual" });
  });

  it("falls back to the first caption track when only auto-generated captions exist", () => {
    expect(choosePreferredCaptionTrack([{ baseUrl: "https://example.com/asr", isAutoGenerated: true }])).toMatchObject({
      baseUrl: "https://example.com/asr"
    });
  });

  it("returns no preferred track when no captions exist", () => {
    expect(choosePreferredCaptionTrack([])).toBeUndefined();
  });

  it("discovers caption tracks from the fetched watch page when the current DOM has no player response", async () => {
    const fetchMock = vi.fn().mockResolvedValue({
      ok: true,
      text: () =>
        Promise.resolve(`
          <script>
            var ytInitialPlayerResponse = {
              "captions": {
                "playerCaptionsTracklistRenderer": {
                  "captionTracks": [
                    { "baseUrl": "https://www.youtube.com/api/timedtext?v=abc&lang=en", "languageCode": "en" }
                  ]
                }
              }
            };
          </script>
        `)
    });
    vi.stubGlobal("fetch", fetchMock);

    await expect(discoverYouTubeCaptionTracks(document, "https://www.youtube.com/watch?v=abc")).resolves.toEqual([
      {
        baseUrl: "https://www.youtube.com/api/timedtext?v=abc&lang=en",
        languageCode: "en",
        name: undefined,
        isAutoGenerated: false
      }
    ]);
    expect(fetchMock).toHaveBeenCalledWith("https://www.youtube.com/watch?v=abc");
  });

  it("does not fetch the watch page when the current DOM already has caption tracks", async () => {
    document.body.innerHTML = `
      <script>
        var ytInitialPlayerResponse = {
          "captions": {
            "playerCaptionsTracklistRenderer": {
              "captionTracks": [
                { "baseUrl": "https://www.youtube.com/api/timedtext?v=abc&lang=en", "languageCode": "en" }
              ]
            }
          }
        };
      </script>
    `;
    const fetchMock = vi.fn();
    vi.stubGlobal("fetch", fetchMock);

    await expect(discoverYouTubeCaptionTracks(document, "https://www.youtube.com/watch?v=abc")).resolves.toHaveLength(1);
    expect(fetchMock).not.toHaveBeenCalled();
  });

  it("returns no discovered caption tracks when the watch page request fails", async () => {
    vi.stubGlobal("fetch", vi.fn().mockResolvedValue({ ok: false, text: () => Promise.resolve("") }));

    await expect(discoverYouTubeCaptionTracks(document, "https://www.youtube.com/watch?v=abc")).resolves.toEqual([]);
  });
});

describe("caption cue parsing", () => {
  it("parses YouTube json3 timed text", () => {
    expect(
      parseJson3CaptionCues({
        events: [
          { tStartMs: 1000, dDurationMs: 2000, segs: [{ utf8: "Hello" }, { utf8: " world" }] },
          { tStartMs: 3000, dDurationMs: 1000, segs: [{ utf8: "\n" }] }
        ]
      })
    ).toEqual([{ id: "cue-0", startMs: 1000, durationMs: 2000, text: "Hello world" }]);
  });

  it("handles sparse json3 caption events", () => {
    expect(parseJson3CaptionCues({ events: [{ segs: [{ utf8: "Untimed caption" }] }, {}] })).toEqual([
      { id: "cue-0", startMs: 0, durationMs: 0, text: "Untimed caption" }
    ]);
    expect(parseJson3CaptionCues({})).toEqual([]);
  });

  it("filters caption events without readable text", () => {
    expect(parseJson3CaptionCues({ events: [{ segs: [{}] }] })).toEqual([]);
    expect(parseXmlCaptionCues(`<transcript><text start="1" dur="1"></text></transcript>`)).toEqual([]);
  });

  it("parses XML timed text and decodes entities", () => {
    expect(parseXmlCaptionCues(`<transcript><text start="1.5" dur="2">Tom &amp;amp; Jerry</text></transcript>`)).toEqual([
      { id: "cue-0", startMs: 1500, durationMs: 2000, text: "Tom & Jerry" }
    ]);
  });

  it("uses zero timing for malformed XML timestamps", () => {
    expect(parseXmlCaptionCues(`<transcript><text start="bad" dur="">No timing</text></transcript>`)).toEqual([
      { id: "cue-0", startMs: 0, durationMs: 0, text: "No timing" }
    ]);
  });

  it("fetches captions as json3 by appending the format parameter", async () => {
    const fetchMock = vi.fn().mockResolvedValue({
      ok: true,
      headers: new Headers({ "content-type": "application/json" }),
      text: () =>
        Promise.resolve(
          JSON.stringify({
            events: [{ tStartMs: 1000, dDurationMs: 2000, segs: [{ utf8: "Hello" }] }]
          })
        )
    });
    vi.stubGlobal("fetch", fetchMock);

    await expect(
      fetchYouTubeCaptionCues({ baseUrl: "https://www.youtube.com/api/timedtext?v=abc&lang=en", isAutoGenerated: false })
    ).resolves.toEqual([{ id: "cue-0", startMs: 1000, durationMs: 2000, text: "Hello" }]);
    expect(fetchMock).toHaveBeenCalledWith("https://www.youtube.com/api/timedtext?v=abc&lang=en&fmt=json3");
  });

  it("parses fetched JSON captions even without a JSON content type", async () => {
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        ok: true,
        headers: new Headers(),
        text: () => Promise.resolve(JSON.stringify({ events: [{ segs: [{ utf8: "No content type" }] }] }))
      })
    );

    await expect(
      fetchYouTubeCaptionCues({ baseUrl: "https://www.youtube.com/api/timedtext?v=abc&lang=en", isAutoGenerated: false })
    ).resolves.toEqual([{ id: "cue-0", startMs: 0, durationMs: 0, text: "No content type" }]);
  });

  it("parses fetched XML captions when json3 is unavailable", async () => {
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        ok: true,
        headers: new Headers({ "content-type": "text/xml" }),
        text: () => Promise.resolve(`<transcript><text start="2" dur="1">Hello XML</text></transcript>`)
      })
    );

    await expect(
      fetchYouTubeCaptionCues({ baseUrl: "https://www.youtube.com/api/timedtext?v=abc&lang=en", isAutoGenerated: false })
    ).resolves.toEqual([{ id: "cue-0", startMs: 2000, durationMs: 1000, text: "Hello XML" }]);
  });

  it("throws when a caption track request fails", async () => {
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue({
        ok: false,
        status: 429,
        headers: new Headers(),
        text: () => Promise.resolve("")
      })
    );

    await expect(
      fetchYouTubeCaptionCues({ baseUrl: "https://www.youtube.com/api/timedtext?v=abc&lang=en", isAutoGenerated: false })
    ).rejects.toThrow("Caption track request failed with 429.");
  });
});
